const PRODUCT_LIST = [
    {
        id:1,
        image:"./image/home/dress-blue.png",
        title: "Gucci",
        subtitle:"Zipper Mini Dress",
        price: "$879.00",
        heart: true,
        recicle:true,
        leaf:true,
        rabbit:true,
    },
    {
        id:2,
        image:"./image/home/dress-red.png",
        title: "Alexander wang",
        subtitle:"Mix Pattern Leather Jacket",
        price: "$879.00",
        heart: false,
        recicle:true,
        leaf:true,
        rabbit:false,
       
    },
    {
        id:3,
        image:"./image/home/dress-blue.png",
        title: "Gucci",
        subtitle:"Zipper Mini Dress",
        price: "$879.00",
        heart: false,
        recicle:true,
        leaf:true,
        rabbit:true,
        
    },
    {
        id:4,
        image:"./image/home/dress-red.png",
        title: "Gucci",
        subtitle:"Zipper Mini Dress",
        price: "$879.00",
        heart: true,
        recicle:false,
        leaf:false,
        rabbit:true,
    },
    {
        id:5,
        image:"./image/home/dress-blue.png",
        title: "Alexander wang",
        subtitle:"Mix Pattern Leather Jacket",
        price: "$879.00",
        heart: false,
        recicle:false,
        leaf:false,
        rabbit:false,
    },
    {
        id:6,
        image:"./image/home/dress-red.png",
        title: "Gucci",
        subtitle:"Zipper Mini Dress",
        price: "$879.00",
        heart: false,
        recicle:false,
        leaf:false,
        rabbit:false,
    },
]